namespace ODrive.Enums
{
    public enum AxisState
    {
        AXIS_STATE_UNDEFINED = 0,
        AXIS_STATE_IDLE = 1,
        AXIS_STATE_STARTUP_SEQUENCE = 2,
        AXIS_STATE_FULL_CALIBRATION_SEQUENCE = 3,
        AXIS_STATE_MOTOR_CALIBRATION = 4,
        AXIS_STATE_SENSORLESS_CONTROL = 5,
        AXIS_STATE_ENCODER_INDEX_SEARCH = 6,
        AXIS_STATE_ENCODER_OFFSET_CALIBRATION = 7,
        AXIS_STATE_CLOSED_LOOP_CONTROL = 8
    }
}